apiVersion: apps/v1
kind: Deployment
metadata:
  name: dissertation-ai-canary
  namespace : bits-dissertation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dissertation-ai-canary
  template:
    metadata:
      labels:
        app: dissertation-ai-canary
    spec:
      containers:
      - name: dissertation-ai-canary
        image: bits2025.azurecr.io/bits-pilani-dissertation-ai-canary:14-bc5993
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
      imagePullSecrets:
      - name: azure-bits-test-local
