apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "0"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: dissertation-ai-canary
  namespace: bits-dissertation
spec:
  ingressClassName: nginx
  rules:
  - host: myapp.48.194.48.34.nip.io
    http:
      paths:
      - backend:
          service:
            name: dissertation-ai-canary
            port:
              number: 80
        path: /
        pathType: Prefix
